declare interface SuccessHttpResponse<T> {
  success: boolean
  message: string
  data: T
}
declare interface ErrorResponse {
  status: number
  data: ErrorHttpResponse
}

declare interface ErrorHttpResponse {
  status: number
  message: string
  success: boolean
}

//Auth Types
declare interface LoginData {
  email: string
  password: string
}

declare interface SignupData extends LoginData {
  confirm_password: string
  terms: boolean
  fullname: string
}

// Generated by https://quicktype.io

declare interface Auth {
  user: User
  token: string
}

declare interface User {
  _id: string
  fullname: string
  email: string
  profile_img?: string
  role: string
  createdAt: string
  updatedAt: string
  __v: number
}

// QUiz Types
declare interface Quiz {
  _type: string
  _id: string
  _updatedAt: string
  description?: string
  creator: Reference
  _createdAt: string
  publish: boolean
  _rev: string
  plays: number
  title: string
  rounds: Round[]
}

declare interface Round {
  round_name: string
  round_type: string
  _type: string
  questions: QuestionElement[]
  _key: string
  category: string
  timer: number
}

declare interface Reference {
  _ref: string
  _type: string
}

declare interface QuestionElement {
  _type: string
  _key: string
  answer: Answer
  question: QuestionQuestion
}

declare interface Answer {
  answer_text: string
  is_blackbox?: boolean
}

declare interface QuestionQuestion {
  question_text: string
  number: number
  question_type: string
  question_image?: Asset
  multi_choice_options?: string[]
  question_video?: Asset
  standalone_asset: boolean
  asset_type: string
}

declare interface Asset {
  _type: string
  asset: Reference
}
