export const quizzes: Quiz[] = [
  {
    _type: 'quiz',
    _id: 'quiz1',
    _updatedAt: '2024-10-01T12:00:00Z',
    creator: { _ref: 'user1', _type: 'reference' },
    _createdAt: '2024-09-01T08:00:00Z',
    publish: true,
    _rev: '1',
    plays: 100,
    title: 'General Knowledge Quiz',
    rounds: [
      {
        round_name: 'Round 1',
        round_type: 'trivia',
        _type: 'round',
        questions: [
          {
            _type: 'question',
            _key: 'q1',
            answer: { answer_text: 'Paris' },
            question: {
              question_text: 'What is the capital of France?',
              number: 1,
              question_type: 'multiple_choice',
              multi_choice_options: ['Paris', 'London', 'Berlin', 'Madrid'],
              standalone_asset: false,
              asset_type: 'none',
            },
          },
          {
            _type: 'question',
            _key: 'q2',
            answer: { answer_text: '5' },
            question: {
              question_text: 'How many oceans are there on Earth?',
              number: 2,
              question_type: 'multiple_choice',
              multi_choice_options: ['3', '5', '7', '4'],
              standalone_asset: false,
              asset_type: 'none',
            },
          },
          {
            _type: 'question',
            _key: 'q3',
            answer: { answer_text: 'true' },
            question: {
              question_text: 'The Earth is round.',
              number: 1,
              question_type: 'true_or_false',
              standalone_asset: false,
              asset_type: 'none',
            },
          },
        ],
        _key: 'round1',
        category: 'Geography',
        timer: 30,
      },
      {
        round_name: 'Round 2',
        round_type: 'dealers_choice',
        _type: 'round',
        questions: [
          {
            _type: 'question',
            _key: 'q1',
            answer: { answer_text: 'Paris' },
            question: {
              question_text: 'What is the capital of France?',
              number: 1,
              question_type: 'open_question',
              standalone_asset: false,
              asset_type: 'none',
            },
          },
          {
            _type: 'question',
            _key: 'q2',
            answer: { answer_text: '5' },
            question: {
              question_text: 'How many oceans are there on Earth?',
              number: 2,
              question_type: 'open_question',
              standalone_asset: false,
              asset_type: 'none',
            },
          },
          {
            _type: 'question',
            _key: 'q3',
            answer: { answer_text: 'true' },
            question: {
              question_text: 'The Earth is round.',
              number: 1,
              question_type: 'open_question',
              standalone_asset: false,
              asset_type: 'none',
            },
          },
        ],
        _key: 'round2',
        category: 'Science',
        timer: 15,
      },
    ],
  },
]
